### ISSUE TITLE
Cherry and KailH switches

### ISSUE THREAD

**Issue by jcagigal** [HenrykRichter/A500KB#2]
Hi! Thanks for sharing this awesome project, could you please let us know which Cherry and KailH switches references could be used? Would it accept different kind of pc keyboard-like keys? Best regards, Jaime.

**Comment by HenrykRichter** [comment]
The design is prepared for classic Cherry switches (any color) with or without mounting/centering pin. KailH and Gateron switches have the same outer parameters. I've test-fitted Cherry White and KailH Box-brown.  One of my Keyboards is built using Cherry Blue (clicky) switches and is equipped with keycaps originating from an old A2000 keyboard (which I didn't get alongside the caps).

Right now I haven't tried to obtain a full keyset (keycaps) from aftermarket vendors. The main challenge would be to get 9U space bars. Also, due to different widths of F1-F10, DEL, HELP and others, a non sculptured profile like DCS would be a good start.
