### ISSUE TITLE
CTRL key implementation

### ISSUE THREAD

**Issue by kavanoz64** [HenrykRichter/A500KB#5]
Hi Henryk,

Thank you for this great project and the support you have been providing. I finally built the keyboard and got it working. So far my testing shows all the keys as working except the CTRL key. CTRL+AMIGA+AMIGA is working to reset the computer so physical connection with the switch should not be an issue.

AmigaOS Documentation Wiki (https://wiki.amigaos.net/wiki/Keymap_Library) says: "When pressed with CTRL alone, alphabetic keys should generally transmit their unshifted value but with bits 5 and 6 cleared. This allows keyboard typing of "control characters." For example, the C key (normally value $63) should transmit value $03 (Ctrl-C) when Ctrl and C are pressed together."

I looked at the source code for the ATMega32 and couldn't see the code to accomplish this (though I am not an expert on this and may have missed it). Can you please confirm if this is the case and whether you are planning to add the functionality?

**Comment by gotnull** [comment]
Can you please go through the firmware flashing process? I've built my own keyboards but wasn't sure what software to use to flash and what pins to use.

**Comment by kavanoz64** [comment]
Today, I installed TF536 and booted to Amiga OS using CF-IDE. I ran the config app, adjusted my led colors and saved to EEPROM. Later when trying a few other things, I noticed in ATK that CTRL key was working. Then I tried CTRL+C and it successfully executed break operation on a running app in the CLI. So the key is working after all.

**Comment by kavanoz64** [comment]
Closing this issue as it wasn't an issue after all.

**Comment by HenrykRichter** [comment]
:-)
The keyboard does not contain modifier logic. It just transmits scancodes that are interpreted by the system (keymap.library) wrt. qualifiers. The only exception is the 3 finger salute.

**Comment by kavanoz64** [comment]
Tonight, I tried again with the 68000 CPU and CTRL didn't work again. Then I tried with Matze's 68030-TK2 and it worked. So on my A500 (rev 6 with 1 MB RAM), it only works with accelerators so far. I have another A500 and a 500+. I'll try with them as well.

**Comment by HenrykRichter** [comment]
I don't think that this CTRL issue is related to the Amiga connection or the firmware since all keycodes are transmitted in exactly the same way. Are you on the latest firmware (from 2-Aug)? I've changed the timing for subsequent (or simultaneuos) keycode transmission to wait a little longer between transmitted keystrokes in that version. I just checked CTRL-C with a slow (68010) A500 and it worked just fine for me.

What I suspect is an electrical issue, where there is either a soldering problem (pls check pin 13 of the ATMega) or the particular switch has a connectivity problem (internal or external). I found that I had to clean the pins of my Mitsumi switches before soldering when I've built my Keyboards.
